### ISSUE TITLE
On defining separate methods for Pythons 2 and 3

### ISSUE THREAD

**Issue by ghost** [iliana/python-simplemediawiki#5]
[Here](https://github.com/ianweller/python-simplemediawiki/commit/edd41b0d53c4f892a61004a2e69851b5b6a85911#simplemediawiki.py), you added `if sys.version[blah]` in the body of a method.

When you import it, the `sys.version` is already static, every line of code will be running in the same interpreter which you already know is 2.7.4 or 3.3.1 or something. Putting an `if` statement like that in the body of the method is saying "HEY WHAT VERSION IS THIS" every time you call the method.

We do not know the version beforehand. But we can define a method for Python 2 and another one for Python 3. Another `if` statement can check the Python version once, and then set the corresponding method for the class. This would decrease the method call time and make debugging clearer.

**Comment by iliana** [comment]
(We discussed this in IRC a while back.)

I am closing this wontfix. It's my belief that the way I've done it makes code more readable — it's clear that different things are happening based on your Python version when you read the function definition, instead of (for instance, a new person looking at the code) chasing down what the method is called, where it's set, and realizing it's one of two methods depending on what version is being run.

I don't think there is an important performance benefit by changing it to check the Python version once. I'm open to discussion on this if some actual numbers can be posted.
